### PR TITLE
fix: allow `null` for `statePropName`

### LINKED ISSUE #267: allow `null` for `statePropName`
> - [ ] `statePropName` cannot be set to `null`, you currently have to set an empty string. I've seen this in other places too. This is an unexpected because as a general rule, the absence of a value should be represented by `null`. Only in very rare cases empty strings should be used.

### PR DESCRIPTION
**Pull request by louisameline**
fixes #267 
Allow `statePropName` to be `null`

### CODE REVIEW

File: src/module/errorCheckConfig.ts [hunk 1]
```diff
@@ -16,7 +16,10 @@ export default function (config: IEasyFirestoreModule): boolean {
       errors.push(`Missing \`${prop}\` in your module!`)
     }
   })
-  if (/(\.|\/)/.test(config.statePropName)) {
+  if (config.statePropName !== null && !isString(config.statePropName)) {
+    errors.push('statePropName must be null or a string')
```
Comment (mesqueeb) [inline src/module/errorCheckConfig.ts]: Can you change to:
`'statePropName must be null or a string without special characters'`

**Comment by mesqueeb** [comment]
@louisameline I went over your PR, looks ok besides the one comment.

Did you run the tests? They should all pass besides 3 tests that are manual deletion tests, which you shouldn't worry about 😄 

If you make the requested change & ran the tests I'll merge.

Please change the base branch to `dev`.

**Comment by louisameline** [comment]
Yes, the tests ran fine except those three. I squashed the wording change into the previous editions as requested. Thank you!
